# Generated by Django 4.0.3 on 2022-03-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('pid', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=200)),
                ('town', models.CharField(max_length=30)),
                ('zip_code', models.SmallIntegerField()),
                ('phone', models.IntegerField()),
                ('price', models.IntegerField()),
                ('comment', models.TextField()),
                ('qty', models.SmallIntegerField()),
            ],
        ),
    ]
