# Generated by Django 4.0.3 on 2022-03-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_remove_order_price_remove_order_qty_remove_order_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pid',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='qty',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='uid',
            field=models.IntegerField(default=1),
        ),
    ]
