# Generated by Django 4.0.3 on 2022-03-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_order_pid_order_price_order_qty_order_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='qty',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.IntegerField(),
        ),
    ]
