# Generated by Django 4.0.3 on 2022-03-06 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_catagory_product_catagory'),
    ]

    operations = [
        migrations.CreateModel(
            name='subCatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sub_catagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.subcatagory'),
        ),
    ]
