# Generated by Django 4.0.3 on 2022-03-06 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_subcatagory_product_sub_catagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_catagory',
        ),
        migrations.DeleteModel(
            name='subCatagory',
        ),
    ]
