# Generated by Django 4.0.3 on 2022-03-08 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_customer_product_delivery_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
