# Generated by Django 4.0.3 on 2022-03-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_name_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='pid',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, unique=True),
        ),
    ]
