# Generated by Django 4.0.3 on 2022-03-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_product_id_product_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
