# Generated by Django 4.0.3 on 2022-03-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_product_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
