# Generated by Django 4.0.3 on 2022-03-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_product_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantiles',
            field=models.SmallIntegerField(default='1'),
        ),
    ]
