# Generated by Django 4.0.3 on 2022-03-10 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_products_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='quantiles',
        ),
    ]
