# Generated by Django 4.0.3 on 2022-03-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0002_delete_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartItem',
            fields=[
                ('cid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('qty', models.SmallIntegerField()),
                ('in_cart', models.BooleanField(default=True)),
            ],
        ),
    ]
